#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_add.verilog
rv32mi_test_inst += rv32mi_and.verilog
rv32mi_test_inst += rv32mi_or.verilog
rv32mi_test_inst += rv32mi_sll.verilog
rv32mi_test_inst += rv32mi_slt.verilog
rv32mi_test_inst += rv32mi_sltu.verilog
rv32mi_test_inst += rv32mi_sra.verilog
rv32mi_test_inst += rv32mi_srl.verilog
rv32mi_test_inst += rv32mi_sub.verilog
rv32mi_test_inst += rv32mi_xor.verilog

#=======================================================================
