#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_add
rv32mi_test_inst += rv32mi_and
rv32mi_test_inst += rv32mi_or
rv32mi_test_inst += rv32mi_sll
rv32mi_test_inst += rv32mi_slt
rv32mi_test_inst += rv32mi_sltu
rv32mi_test_inst += rv32mi_sra
rv32mi_test_inst += rv32mi_srl
rv32mi_test_inst += rv32mi_sub
rv32mi_test_inst += rv32mi_xor

#=======================================================================
