#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_addi
rv32mi_test_inst += rv32mi_andi
rv32mi_test_inst += rv32mi_jalr
rv32mi_test_inst += rv32mi_lb
rv32mi_test_inst += rv32mi_lbu
rv32mi_test_inst += rv32mi_lh
rv32mi_test_inst += rv32mi_lhu
rv32mi_test_inst += rv32mi_lw
rv32mi_test_inst += rv32mi_ori
rv32mi_test_inst += rv32mi_slli
rv32mi_test_inst += rv32mi_slti
rv32mi_test_inst += rv32mi_sltiu
rv32mi_test_inst += rv32mi_srai
rv32mi_test_inst += rv32mi_srli
rv32mi_test_inst += rv32mi_xori

#=======================================================================
