#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_addi.verilog
rv32mi_test_inst += rv32mi_andi.verilog
rv32mi_test_inst += rv32mi_jalr.verilog
rv32mi_test_inst += rv32mi_lb.verilog
rv32mi_test_inst += rv32mi_lbu.verilog
rv32mi_test_inst += rv32mi_lh.verilog
rv32mi_test_inst += rv32mi_lhu.verilog
rv32mi_test_inst += rv32mi_lw.verilog
rv32mi_test_inst += rv32mi_ori.verilog
rv32mi_test_inst += rv32mi_slli.verilog
rv32mi_test_inst += rv32mi_slti.verilog
rv32mi_test_inst += rv32mi_sltiu.verilog
rv32mi_test_inst += rv32mi_srai.verilog
rv32mi_test_inst += rv32mi_srli.verilog
rv32mi_test_inst += rv32mi_xori.verilog

#=======================================================================
