#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_beq
rv32mi_test_inst += rv32mi_bge
rv32mi_test_inst += rv32mi_bgeu
rv32mi_test_inst += rv32mi_blt
rv32mi_test_inst += rv32mi_bltu
rv32mi_test_inst += rv32mi_bne

#=======================================================================
