#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_beq
rv32mi_test_inst += rv32mi_bge
rv32mi_test_inst += rv32mi_bge_n
rv32mi_test_inst += rv32mi_bgeu
rv32mi_test_inst += rv32mi_bgeu_n
rv32mi_test_inst += rv32mi_blt
rv32mi_test_inst += rv32mi_blt_n
rv32mi_test_inst += rv32mi_bltu
rv32mi_test_inst += rv32mi_bltu_n
rv32mi_test_inst += rv32mi_bne
rv32mi_test_inst += rv32mi_bne_n

#=======================================================================
