#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_sb.verilog
rv32mi_test_inst += rv32mi_sh.verilog
rv32mi_test_inst += rv32mi_sw.verilog

#=======================================================================
