#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_div
rv32mi_test_inst += rv32mi_divu
rv32mi_test_inst += rv32mi_mul
rv32mi_test_inst += rv32mi_mulh
rv32mi_test_inst += rv32mi_mulhsu
rv32mi_test_inst += rv32mi_mulhu
rv32mi_test_inst += rv32mi_rem
rv32mi_test_inst += rv32mi_remu

#=======================================================================
