#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_div.verilog
rv32mi_test_inst += rv32mi_mul.verilog
rv32mi_test_inst += rv32mi_mulh.verilog
rv32mi_test_inst += rv32mi_rem.verilog

#=======================================================================
