#=======================================================================
# brief: Makefile for add object
# author: macro
# date: 2023/08/30
# changelog:
#=======================================================================
rv32mi_test_inst += rv32mi_div
rv32mi_test_inst += rv32mi_mul
rv32mi_test_inst += rv32mi_mulh
rv32mi_test_inst += rv32mi_rem

#=======================================================================
